replicaCount: 1
image:
  repository: shelleg/msa-api
  tag: 0.1.6
  pullPolicy: Always
nameOverride: msa-api
fullnameOverride: msa-api
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
namespace: msa-api
