apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "msa-api.fullname" . }}
  labels:
    app: {{ include "msa-api.name" . }}
    chart: {{ include "msa-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "msa-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "msa-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.node }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-file
              mountPath: /opt/tikal/config
          livenessProbe:
            httpGet:
              path: /probe/liveness
              port: 8080
            initialDelaySeconds: {{ .Values.livinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livinessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /probe/readiness
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      volumes:
        - name: config-file
          configMap:
            name: {{ include "msa-api.fullname" . }}-cm
            items:
              - key: config.json
                path: docker.json
